-- Migración 002: Grupos de compatibilidad de modelos (micas/pantallas que comparten pieza física)
-- Motor: PostgreSQL (Supabase, proyecto flfhpffslhjcuvhxsnjz)
--
-- CONTEXTO: en BlackHouse OS, ciertas micas y pantallas sirven físicamente para varios
-- modelos de celular a la vez (ej. "la mica del Note 11 le hace al Note 10s"). Hoy esa
-- información vive solo como texto libre en productos.modelo_compatible ("Modelo A / Modelo B"),
-- sin ninguna estructura consultable. Estas tablas modelan esos "grupos de compatibilidad"
-- de forma explícita: un grupo puede tener 2, 3, 4+ modelos miembro.
--
-- DISEÑO: se usa el patrón "grupo con miembros" (no pares modelo-A/modelo-B) porque los
-- fabricantes publican compatibilidad como listas de N modelos, y así se evita la
-- explosión combinatoria y la necesidad de clausura transitiva que tendría un modelo de pares.
--
-- SEGURIDAD: se habilita el flag RLS por consistencia con TODAS las demás tablas de este
-- proyecto (todas tienen rls_enabled=true), pero SIN políticas — igual que
-- subcategorias_personalizadas y cargas_procesadas, que tampoco tienen políticas hoy.
-- Verificado con `SELECT * FROM pg_policies` antes de escribir esto: no hay ninguna política
-- real en producción. La app usa la service_role key (bypassa RLS) en main.js y api/db.js;
-- la autorización real ocurre en la capa de aplicación (variable rolActual en main.js,
-- matriz PERMISOS_POR_ROL en api/db.js). No se agregan políticas nuevas para no introducir
-- un patrón de seguridad que el resto del sistema no usa.
--
-- Nota: existe un archivo scripts/sql/migrations/001_rls_inventario_vendedor.sql en este
-- mismo repo que sí define roles/políticas RLS (admin_role, pos_vendedor, vw_productos_pos),
-- pero referencia columnas que NO existen en la tabla productos real (stock_disponible,
-- precio_venta, costo_proveedor, margen) — es una plantilla genérica no aplicada a este
-- proyecto, no un patrón vigente. Esta migración 002 sigue el esquema real verificado por
-- SELECT contra information_schema.columns, no el archivo 001.

BEGIN;

-- 1. Grupos de compatibilidad: una fila = un grupo de modelos que comparten la misma pieza física.
CREATE TABLE public.grupos_compatibilidad (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id  text NOT NULL,
    tipo_pieza  text NOT NULL CHECK (tipo_pieza IN ('mica', 'pantalla', 'general')),
    etiqueta    text NOT NULL,               -- texto legible, ej. "Galaxy A12 / A20s"
    creado_en   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_grupos_compatibilidad_empresa ON public.grupos_compatibilidad(empresa_id);

COMMENT ON TABLE public.grupos_compatibilidad IS
    'Grupos de modelos que comparten la misma pieza física (misma mica/pantalla, mismo stock). tipo_pieza distingue el tipo porque la compatibilidad de una mica no implica compatibilidad de pantalla entre los mismos modelos.';

-- 2. Miembros de cada grupo (N modelos por grupo, sin límite).
CREATE TABLE public.grupos_compatibilidad_modelos (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_id            bigint NOT NULL REFERENCES public.grupos_compatibilidad(id) ON DELETE CASCADE,
    marca               text,                -- nullable: no todos los fragmentos de texto histórico traen marca explícita
    modelo              text NOT NULL,
    modelo_normalizado  text NOT NULL,       -- UPPER + espacios colapsados, para matching en búsqueda/Excel
    UNIQUE (grupo_id, modelo_normalizado)
);

CREATE INDEX idx_grupos_compat_modelos_grupo ON public.grupos_compatibilidad_modelos(grupo_id);
CREATE INDEX idx_grupos_compat_modelos_normalizado ON public.grupos_compatibilidad_modelos(modelo_normalizado);

COMMENT ON TABLE public.grupos_compatibilidad_modelos IS
    'Modelos miembro de cada grupo de compatibilidad. modelo_normalizado se usa para matching insensible a mayúsculas/espacios en búsqueda e importación de Excel.';

-- 3. Vínculo opcional producto -> grupo (nullable: la mayoría de productos hoy no pertenecen a ningún grupo).
ALTER TABLE public.productos
    ADD COLUMN grupo_compatibilidad_id bigint REFERENCES public.grupos_compatibilidad(id) ON DELETE SET NULL;

CREATE INDEX idx_productos_grupo_compatibilidad ON public.productos(grupo_compatibilidad_id);

-- 4. RLS: habilitado por consistencia de flag con el resto de tablas, sin políticas (ver nota arriba).
ALTER TABLE public.grupos_compatibilidad ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grupos_compatibilidad_modelos ENABLE ROW LEVEL SECURITY;

COMMIT;
