-- Migración 005: módulo de Devoluciones (cliente devuelve un producto vendido)
-- Motor: PostgreSQL (Supabase, proyecto flfhpffslhjcuvhxsnjz)
--
-- Esquema real verificado por lectura (information_schema.columns) antes de escribir esto:
--   - facturas: id bigint, empresa_id bigint (¡ojo! bigint, no text como la mayoría de tablas
--     nuevas — no afecta esta migración porque solo referenciamos facturas.id, no su empresa_id),
--     items_json jsonb (array de {nombre, precio, cantidad, subtotal}, SIN producto_id/sku —
--     puede ser NULL en facturas viejas o ligadas a órdenes de taller sin items). No existe
--     factura_items como tabla separada.
--   - movimientos_stock: empresa_id text, sku text, cantidad integer, proveedor/costo/nota/
--     fecha_ingreso nullable, creado_en timestamptz default now().
--   - Verificado también (information_schema FKs referenciando productos): NINGUNA FK del
--     proyecto apunta hoy a productos.id, así que un producto_id nullable con ON DELETE SET NULL
--     es seguro (no hay riesgo de romper otra relación existente).
--
-- NO APLICADA POR EL AGENTE: solo se prepara el archivo, mismo patrón que 002/003.

BEGIN;

CREATE TABLE public.devoluciones (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      text NOT NULL,
    factura_id      bigint REFERENCES public.facturas(id) ON DELETE SET NULL,
    producto_id     bigint REFERENCES public.productos(id) ON DELETE SET NULL,
    producto_nombre text NOT NULL,
    cantidad        integer NOT NULL CHECK (cantidad > 0),
    motivo          text,
    condicion       text NOT NULL CHECK (condicion IN ('buen_estado', 'defectuoso')),
    accion          text NOT NULL CHECK (accion IN ('reembolso_efectivo', 'nota_credito', 'cambio_producto', 'ninguna')),
    monto           numeric,
    usuario         text,
    creado_en       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_devoluciones_empresa ON public.devoluciones(empresa_id);
CREATE INDEX idx_devoluciones_factura ON public.devoluciones(factura_id);

-- RLS habilitado por consistencia de flag con el resto de tablas del proyecto (todas lo tienen
-- en true), SIN políticas — igual que grupos_compatibilidad, subcategorias_personalizadas y
-- cargas_procesadas. La app usa la service_role key en main.js (bypassa RLS); la autorización
-- real ocurre en la capa de aplicación (empresaActual/rolActual).
ALTER TABLE public.devoluciones ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Verificación sugerida después de aplicar:
--   SELECT column_name, data_type FROM information_schema.columns WHERE table_name='devoluciones';
