-- Migración 006: repuestos consumidos en el taller (descuento de stock por orden de reparación)
-- Motor: PostgreSQL (Supabase, proyecto flfhpffslhjcuvhxsnjz)
--
-- CONTEXTO / PROBLEMA QUE RESUELVE:
--   Hasta hoy, la tabla `ordenes` guarda `precio_repuesto` (un número escrito a mano en
--   Recepción) pero NO tiene ninguna relación con el producto real de inventario. Cuando el
--   técnico instala una pantalla (u otro repuesto) desde el Laboratorio, ese producto nunca se
--   descuenta de `productos.stock`. Resultado: el inventario nunca refleja las piezas gastadas
--   en reparaciones y el dueño pierde el control real del stock.
--
--   Esta tabla registra CADA repuesto consumido por una orden de taller. Es la traza que une
--   orden ↔ pieza real ↔ cantidad, y es la que permite (desde main.js) descontar stock y dejar
--   un movimiento en `movimientos_stock` (salida) por cada consumo, con posibilidad de revertir.
--
-- ESQUEMA REAL VERIFICADO por lectura (information_schema / list_tables) antes de escribir esto:
--   - ordenes: id bigint PK, empresa_id text (nullable), precio_repuesto numeric default 0, ...
--   - productos: id bigint PK, empresa_id text, sku text, stock int4, costo numeric, precio numeric.
--   - movimientos_stock: empresa_id text, sku text, cantidad int4 (negativa = salida), proveedor/
--     costo/nota nullable, creado_en timestamptz default now().
--   Los empresa_id de ordenes/productos/movimientos_stock son text (consistente con esta tabla).
--
-- NO APLICADA POR EL AGENTE EN ESTE ARCHIVO: se deja preparada igual que 002/003/005. El código
-- de main.js asume que ya existe cuando se aplique. (En esta sesión sí se aplicó vía MCP; ver
-- comentario de verificación al final.)

BEGIN;

CREATE TABLE public.orden_repuestos (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id      text    NOT NULL,
    orden_id        bigint  NOT NULL REFERENCES public.ordenes(id) ON DELETE CASCADE,
    producto_id     bigint  REFERENCES public.productos(id) ON DELETE SET NULL,
    sku             text,
    producto_nombre text    NOT NULL,
    cantidad        integer NOT NULL CHECK (cantidad > 0),
    costo_unitario  numeric,          -- costo de la pieza al momento del consumo (para reportes)
    precio_unitario numeric,          -- precio de venta de la pieza al momento del consumo
    usuario         text,             -- técnico que registró el consumo
    creado_en       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_orden_repuestos_empresa ON public.orden_repuestos(empresa_id);
CREATE INDEX idx_orden_repuestos_orden   ON public.orden_repuestos(orden_id);

-- RLS habilitado por consistencia de flag con el resto de tablas del proyecto (todas lo tienen
-- en true), SIN políticas — igual que devoluciones, grupos_compatibilidad y
-- subcategorias_personalizadas. La app usa la service_role key en main.js (bypassa RLS); la
-- autorización real ocurre en la capa de aplicación (empresaActual/rolActual en main.js).
ALTER TABLE public.orden_repuestos ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Verificación sugerida después de aplicar:
--   SELECT column_name, data_type FROM information_schema.columns WHERE table_name='orden_repuestos';
--   -- Consumo de una orden con su total gastado en piezas:
--   SELECT orden_id, sum(cantidad) piezas, sum(cantidad*coalesce(precio_unitario,0)) total_repuestos
--     FROM orden_repuestos GROUP BY orden_id;
