-- Migración 006: Módulo POS de Ventas para la Vendedora (app Android enlazada a la web)
-- Motor: PostgreSQL (Supabase, proyecto flfhpffslhjcuvhxsnjz)
--
-- Objetivo funcional (pedido del dueño):
--   1) La vendedora vende productos que SÍ están en inventario -> descuenta el stock real.
--   2) La vendedora puede vender un producto que NO tiene en inventario (ej. un "chip"):
--      ese producto NO toca el stock ni crea un producto de inventario. Se guarda aparte en
--      productos_venta_libre para que la PRÓXIMA vez ya aparezca disponible para vender, con el
--      precio que ella usó, sin haber agregado stock.
--   3) Al final del día puede hacer "cierre de caja" y obtener el total de las ventas del día.
--
-- Arquitectura de seguridad (importante):
--   La web/APK NO usa la service_role key (esa solo la usa el escritorio en main.js). La web usa
--   la ANON key pública y SOLO puede llamar a las funciones pos_* de abajo. Todas son
--   SECURITY DEFINER y resuelven la empresa a partir de un TOKEN de sesión guardado en
--   pos_sesiones: el cliente nunca envía su empresa_id, así que una vendedora jamás puede leer ni
--   escribir datos de otra empresa. Las tablas tienen RLS activado y SIN permisos directos para
--   anon; el único camino es a través de estas funciones.
--
-- Verificación de esquema hecha antes de escribir (mismo patrón que 002/003/005):
--   - productos: columnas reales nombre, precio, stock, sku, categoria, empresa_id (numérico).
--     OJO: la migración 001 (vw_productos_pos) usaba stock_disponible/precio_venta, que NO existen.
--     Esta migración usa las columnas reales y crea una vista corregida al final.
--   - usuarios: usuario, password (bcrypt $2b$ o texto plano heredado), rol, estado, empresa_id,
--     nombre_completo, nickname, id.
--   - empresas: id, fecha_de_vencimiento.
--   - movimientos_stock: empresa_id text, sku text, cantidad integer, nota nullable, creado_en.
--
-- NO APLICADA POR EL AGENTE: solo se prepara el archivo. Aplícala desde el SQL Editor de Supabase.

BEGIN;

-- pgcrypto: para verificar contraseñas bcrypt (crypt) y generar tokens (gen_random_bytes).
-- En Supabase vive en el esquema "extensions".
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

-- ---------------------------------------------------------------------------
-- 1. TABLAS
-- ---------------------------------------------------------------------------

-- Productos que la vendedora vende SIN tenerlos en inventario. NUNCA tocan productos.stock.
-- Se "recuerdan" por empresa para que reaparezcan en la próxima venta.
CREATE TABLE IF NOT EXISTS public.productos_venta_libre (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id     bigint  NOT NULL,
    nombre         text    NOT NULL,
    precio         numeric NOT NULL DEFAULT 0,
    veces_vendido  integer NOT NULL DEFAULT 0,
    activo         boolean NOT NULL DEFAULT true,
    creado_en      timestamptz NOT NULL DEFAULT now(),
    actualizado_en timestamptz NOT NULL DEFAULT now()
);
-- Un mismo nombre no se duplica por empresa (case-insensitive). Este índice también es el que
-- usa el ON CONFLICT de pos_registrar_venta.
CREATE UNIQUE INDEX IF NOT EXISTS uq_venta_libre_empresa_nombre
    ON public.productos_venta_libre (empresa_id, lower(nombre));

-- Sesiones del POS: el token que la web guarda tras el login. La empresa se resuelve desde acá.
CREATE TABLE IF NOT EXISTS public.pos_sesiones (
    token       text PRIMARY KEY,
    usuario_id  text,          -- text para servir tanto si usuarios.id es entero como UUID
    empresa_id  bigint NOT NULL,
    rol         text,
    usuario     text,
    nombre      text,
    creado_en   timestamptz NOT NULL DEFAULT now(),
    expira_en   timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pos_sesiones_expira ON public.pos_sesiones(expira_en);

-- Cabecera de cada venta (ticket).
CREATE TABLE IF NOT EXISTS public.ventas_pos (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id       bigint  NOT NULL,
    vendedor_id      text,
    vendedor_usuario text,
    total            numeric NOT NULL DEFAULT 0,
    medio_pago       text    NOT NULL DEFAULT 'efectivo',
    cierre_id        bigint,       -- se completa cuando la venta entra en un cierre de caja
    creado_en        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ventas_pos_empresa_fecha ON public.ventas_pos(empresa_id, creado_en);

-- Líneas de cada venta.
CREATE TABLE IF NOT EXISTS public.ventas_pos_items (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id        bigint  NOT NULL REFERENCES public.ventas_pos(id) ON DELETE CASCADE,
    origen          text    NOT NULL CHECK (origen IN ('stock', 'libre')),
    producto_id     bigint,       -- productos.id (stock) o productos_venta_libre.id (libre)
    nombre          text    NOT NULL,
    precio_unitario numeric NOT NULL DEFAULT 0,
    cantidad        numeric NOT NULL DEFAULT 1 CHECK (cantidad > 0),
    subtotal        numeric NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_ventas_pos_items_venta ON public.ventas_pos_items(venta_id);

-- Cierres de caja (una foto del día cuando la vendedora cierra).
CREATE TABLE IF NOT EXISTS public.cierres_caja (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id       bigint  NOT NULL,
    vendedor_usuario text,
    fecha            date    NOT NULL,
    desde            timestamptz NOT NULL,
    hasta            timestamptz NOT NULL,
    total_ventas     numeric NOT NULL DEFAULT 0,
    cantidad_ventas  integer NOT NULL DEFAULT 0,
    total_efectivo   numeric NOT NULL DEFAULT 0,
    total_otros      numeric NOT NULL DEFAULT 0,
    detalle_json     jsonb,
    creado_en        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_cierres_caja_empresa_fecha ON public.cierres_caja(empresa_id, fecha);

-- RLS activado en todas, SIN políticas: nadie entra directo. El acceso es solo vía funciones
-- SECURITY DEFINER (mismo criterio que devoluciones/grupos_compatibilidad en este proyecto).
ALTER TABLE public.productos_venta_libre ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_sesiones          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ventas_pos            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ventas_pos_items      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cierres_caja          ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- 2. FUNCIONES RPC (las únicas que la web puede llamar con la anon key)
-- ---------------------------------------------------------------------------

-- 2.1 LOGIN: valida usuario/contraseña contra usuarios y devuelve un token de sesión.
CREATE OR REPLACE FUNCTION public.pos_login(p_usuario text, p_password text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    -- Variables escalares con tipo (NO usar 'record' + campos dentro de SQL: el validador de
    -- PL/pgSQL puede interpretar la variable como una tabla -> "relation ... does not exist").
    v_id         text;
    v_empresa_id bigint;
    v_rol        text;
    v_hash       text;
    v_nombre     text;
    v_usuario    text;
    v_venc       timestamptz;
    v_ok         boolean := false;
    v_token      text;
BEGIN
    -- Un solo SELECT (con JOIN a empresas) hacia variables escalares.
    SELECT u.id::text, u.empresa_id, u.rol, u.password,
           coalesce(u.nombre_completo, u.nickname, u.usuario), u.usuario,
           e.fecha_de_vencimiento::timestamptz
      INTO v_id, v_empresa_id, v_rol, v_hash, v_nombre, v_usuario, v_venc
      FROM usuarios u
      LEFT JOIN empresas e ON e.id = u.empresa_id
     WHERE u.usuario = p_usuario AND u.estado = 'activo'
     LIMIT 1;

    IF NOT FOUND THEN
        RETURN json_build_object('ok', false, 'msg', 'Usuario no encontrado o inactivo');
    END IF;

    -- Solo roles con acceso al POS de ventas.
    IF coalesce(v_rol, '') NOT IN ('vendedor', 'vendedora', 'dueno', 'admin', 'administrador') THEN
        RETURN json_build_object('ok', false, 'msg', 'Este usuario no tiene acceso al POS de ventas');
    END IF;

    IF v_hash IS NULL THEN
        v_ok := false;
    ELSIF v_hash LIKE '$2%' THEN
        -- bcrypt: normalizamos el prefijo $2b$/$2y$ a $2a$ para que crypt() lo verifique.
        v_ok := crypt(p_password, regexp_replace(v_hash, '^\$2[aby]\$', '$2a$'))
                = regexp_replace(v_hash, '^\$2[aby]\$', '$2a$');
    ELSE
        v_ok := (v_hash = p_password);  -- contraseña en texto plano heredada
    END IF;

    IF NOT v_ok THEN
        RETURN json_build_object('ok', false, 'msg', 'Contraseña incorrecta');
    END IF;

    -- Vencimiento de licencia de la empresa (mismo criterio que el escritorio).
    IF v_empresa_id <> 1 AND v_venc IS NOT NULL AND now() > v_venc THEN
        RETURN json_build_object('ok', false, 'msg', 'Licencia vencida. Contacta al administrador.');
    END IF;

    v_token := encode(gen_random_bytes(24), 'hex');
    INSERT INTO pos_sesiones(token, usuario_id, empresa_id, rol, usuario, nombre, expira_en)
    VALUES (v_token, v_id, v_empresa_id, v_rol, v_usuario, v_nombre, now() + interval '12 hours');

    RETURN json_build_object(
        'ok', true,
        'token', v_token,
        'empresa_id', v_empresa_id,
        'rol', v_rol,
        'usuario', v_usuario,
        'nombre', v_nombre
    );
END;
$$;

-- 2.2 PRODUCTOS: catálogo vendible = productos de inventario + productos_venta_libre.
CREATE OR REPLACE FUNCTION public.pos_productos(p_token text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_emp    bigint;
    v_result json;
BEGIN
    SELECT empresa_id INTO v_emp FROM pos_sesiones WHERE token = p_token AND expira_en > now();
    IF v_emp IS NULL THEN
        RETURN json_build_object('ok', false, 'msg', 'Sesión inválida o expirada');
    END IF;

    SELECT json_build_object(
        'ok', true,
        'stock', coalesce((
            SELECT json_agg(json_build_object(
                       'id', p.id, 'nombre', p.nombre, 'precio', p.precio,
                       'stock', p.stock, 'categoria', p.categoria, 'sku', p.sku
                   ) ORDER BY p.nombre)
              FROM productos p
             WHERE p.empresa_id = v_emp
        ), '[]'::json),
        'libre', coalesce((
            SELECT json_agg(json_build_object(
                       'id', l.id, 'nombre', l.nombre, 'precio', l.precio,
                       'veces_vendido', l.veces_vendido
                   ) ORDER BY l.veces_vendido DESC, l.nombre)
              FROM productos_venta_libre l
             WHERE l.empresa_id = v_emp AND l.activo
        ), '[]'::json)
    ) INTO v_result;

    RETURN v_result;
END;
$$;

-- 2.3 REGISTRAR VENTA: crea el ticket, descuenta stock de los productos de inventario y guarda
--     (o actualiza) los productos "libres" sin tocar el inventario.
--     p_items = array JSON de { origen:'stock'|'libre', producto_id, nombre, precio_unitario, cantidad }
CREATE OR REPLACE FUNCTION public.pos_registrar_venta(
    p_token text, p_items jsonb, p_medio_pago text DEFAULT 'efectivo'
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_emp      bigint;
    v_uid      text;
    v_usuario  text;
    v_item     jsonb;
    v_venta_id bigint;
    v_total    numeric := 0;
    v_sub      numeric;
    v_origen   text;
    v_nombre   text;
    v_precio   numeric;
    v_cant     numeric;
    v_pid      bigint;
    v_libre_id bigint;
BEGIN
    SELECT empresa_id, usuario_id, usuario
      INTO v_emp, v_uid, v_usuario
      FROM pos_sesiones WHERE token = p_token AND expira_en > now();
    IF NOT FOUND THEN
        RETURN json_build_object('ok', false, 'msg', 'Sesión inválida o expirada');
    END IF;

    IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
        RETURN json_build_object('ok', false, 'msg', 'La venta no tiene productos');
    END IF;

    INSERT INTO ventas_pos(empresa_id, vendedor_id, vendedor_usuario, medio_pago, total)
    VALUES (v_emp, v_uid, v_usuario,
            coalesce(nullif(trim(p_medio_pago), ''), 'efectivo'), 0)
    RETURNING id INTO v_venta_id;

    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items) LOOP
        v_origen := coalesce(v_item->>'origen', 'libre');
        v_nombre := trim(coalesce(v_item->>'nombre', ''));
        v_precio := coalesce((v_item->>'precio_unitario')::numeric, 0);
        v_cant   := coalesce((v_item->>'cantidad')::numeric, 1);
        IF v_cant <= 0 THEN v_cant := 1; END IF;
        IF v_nombre = '' THEN CONTINUE; END IF;

        v_sub   := round(v_precio * v_cant, 2);
        v_total := v_total + v_sub;

        IF v_origen = 'stock' THEN
            v_pid := nullif(v_item->>'producto_id', '')::bigint;
            -- Descuenta stock SOLO si el producto es de esta empresa (blindaje multi-empresa).
            UPDATE productos
               SET stock = coalesce(stock, 0) - v_cant
             WHERE id = v_pid AND empresa_id = v_emp;

            -- Registro de movimiento de stock (best-effort: nunca rompe la venta).
            BEGIN
                INSERT INTO movimientos_stock(empresa_id, sku, cantidad, nota)
                SELECT v_emp::text, p.sku, (-v_cant)::int, 'Venta POS #' || v_venta_id
                  FROM productos p
                 WHERE p.id = v_pid AND p.empresa_id = v_emp AND p.sku IS NOT NULL;
            EXCEPTION WHEN others THEN
                NULL;
            END;

            INSERT INTO ventas_pos_items(venta_id, origen, producto_id, nombre, precio_unitario, cantidad, subtotal)
            VALUES (v_venta_id, 'stock', v_pid, v_nombre, v_precio, v_cant, v_sub);
        ELSE
            -- Venta libre: recuerda el producto SIN tocar inventario. Actualiza el precio al último
            -- usado y suma una venta al contador. El ON CONFLICT usa uq_venta_libre_empresa_nombre.
            INSERT INTO productos_venta_libre(empresa_id, nombre, precio, veces_vendido)
            VALUES (v_emp, v_nombre, v_precio, 1)
            ON CONFLICT (empresa_id, lower(nombre))
            DO UPDATE SET precio         = EXCLUDED.precio,
                          veces_vendido  = productos_venta_libre.veces_vendido + 1,
                          activo         = true,
                          actualizado_en = now()
            RETURNING id INTO v_libre_id;

            INSERT INTO ventas_pos_items(venta_id, origen, producto_id, nombre, precio_unitario, cantidad, subtotal)
            VALUES (v_venta_id, 'libre', v_libre_id, v_nombre, v_precio, v_cant, v_sub);
        END IF;
    END LOOP;

    UPDATE ventas_pos SET total = v_total WHERE id = v_venta_id;

    RETURN json_build_object('ok', true, 'venta_id', v_venta_id, 'total', v_total);
END;
$$;

-- 2.4 CIERRE DE CAJA: total de las ventas del día. Con p_registrar=true guarda el cierre y marca
--     las ventas como cerradas; con false (default) solo devuelve el resumen para previsualizar.
CREATE OR REPLACE FUNCTION public.pos_cierre_caja(
    p_token text, p_fecha date DEFAULT NULL, p_registrar boolean DEFAULT false
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_emp      bigint;
    v_usuario  text;
    v_fecha    date;
    v_desde    timestamptz;
    v_hasta    timestamptz;
    v_total    numeric;
    v_cant     integer;
    v_efectivo numeric;
    v_otros    numeric;
    v_detalle  json;
    v_cierre_id bigint;
BEGIN
    SELECT empresa_id, usuario
      INTO v_emp, v_usuario
      FROM pos_sesiones WHERE token = p_token AND expira_en > now();
    IF NOT FOUND THEN
        RETURN json_build_object('ok', false, 'msg', 'Sesión inválida o expirada');
    END IF;

    v_fecha := coalesce(p_fecha, (now())::date);
    v_desde := v_fecha::timestamptz;
    v_hasta := (v_fecha + 1)::timestamptz;

    SELECT coalesce(sum(total), 0),
           count(*),
           coalesce(sum(total) FILTER (WHERE medio_pago = 'efectivo'), 0),
           coalesce(sum(total) FILTER (WHERE medio_pago <> 'efectivo'), 0)
      INTO v_total, v_cant, v_efectivo, v_otros
      FROM ventas_pos
     WHERE empresa_id = v_emp
       AND creado_en >= v_desde AND creado_en < v_hasta;

    SELECT coalesce(json_agg(x ORDER BY x.subtotal DESC), '[]'::json) INTO v_detalle
      FROM (
            SELECT i.nombre, i.origen,
                   sum(i.cantidad) AS cantidad,
                   sum(i.subtotal) AS subtotal
              FROM ventas_pos_items i
              JOIN ventas_pos v ON v.id = i.venta_id
             WHERE v.empresa_id = v_emp
               AND v.creado_en >= v_desde AND v.creado_en < v_hasta
             GROUP BY i.nombre, i.origen
      ) x;

    IF p_registrar THEN
        INSERT INTO cierres_caja(empresa_id, vendedor_usuario, fecha, desde, hasta,
                                 total_ventas, cantidad_ventas, total_efectivo, total_otros, detalle_json)
        VALUES (v_emp, v_usuario, v_fecha, v_desde, v_hasta,
                v_total, v_cant, v_efectivo, v_otros, v_detalle)
        RETURNING id INTO v_cierre_id;

        UPDATE ventas_pos SET cierre_id = v_cierre_id
         WHERE empresa_id = v_emp
           AND creado_en >= v_desde AND creado_en < v_hasta
           AND cierre_id IS NULL;
    END IF;

    RETURN json_build_object(
        'ok', true,
        'fecha', v_fecha,
        'total_ventas', v_total,
        'cantidad_ventas', v_cant,
        'total_efectivo', v_efectivo,
        'total_otros', v_otros,
        'detalle', v_detalle,
        'cierre_id', v_cierre_id,
        'registrado', p_registrar
    );
END;
$$;

-- ---------------------------------------------------------------------------
-- 3. PERMISOS: la web (anon) SOLO puede ejecutar estas funciones. Nada de acceso directo a tablas.
-- ---------------------------------------------------------------------------
REVOKE ALL ON FUNCTION public.pos_login(text, text)                     FROM public;
REVOKE ALL ON FUNCTION public.pos_productos(text)                       FROM public;
REVOKE ALL ON FUNCTION public.pos_registrar_venta(text, jsonb, text)    FROM public;
REVOKE ALL ON FUNCTION public.pos_cierre_caja(text, date, boolean)      FROM public;

GRANT EXECUTE ON FUNCTION public.pos_login(text, text)                  TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pos_productos(text)                    TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pos_registrar_venta(text, jsonb, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pos_cierre_caja(text, date, boolean)   TO anon, authenticated;

-- ---------------------------------------------------------------------------
-- 4. Vista corregida vw_productos_pos (la de la migración 001 usaba columnas inexistentes).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW public.vw_productos_pos AS
    SELECT id, empresa_id, nombre, stock AS stock_disponible, precio AS precio_venta
      FROM public.productos;

COMMIT;

-- ---------------------------------------------------------------------------
-- Verificación sugerida después de aplicar:
--   SELECT public.pos_login('usuario_vendedora', 'su_password');  -- debe devolver ok:true + token
--   SELECT public.pos_productos('<token>');
--   SELECT public.pos_cierre_caja('<token>');
-- Limpieza opcional de sesiones vencidas (correr por cron o a mano):
--   DELETE FROM public.pos_sesiones WHERE expira_en < now();
