-- Migración 007: Compras externas de repuestos (traídos de otro proveedor)
-- Motor: PostgreSQL (Supabase, proyecto flfhpffslhjcuvhxsnjz)
--
-- Para qué: cuando se acaba un repuesto en stock y el técnico/dueño lo trae de OTRO proveedor
-- para completar una reparación, se registra aquí: de qué proveedor, qué repuesto y cuánto se
-- pagó. Así, al cerrar el día, se sabe a quién hay que pagarle y cuánto se gastó con externos.
-- NO toca el inventario (no es un producto propio; nunca estuvo en stock).
--
-- Esquema verificado: ordenes.id (referenciado solo por valor, guardamos orden_id como text para
-- no atarnos al tipo). empresa_id numérico como en productos/ordenes.
--
-- La app usa la service_role key en main.js (bypassa RLS); RLS se activa por consistencia.

BEGIN;

CREATE TABLE IF NOT EXISTS public.compras_externas (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id  bigint  NOT NULL,
    orden_id    text,                       -- # de orden donde se usó (opcional)
    proveedor   text    NOT NULL,
    descripcion text,                        -- qué repuesto (ej. "Pantalla A15 INCELL")
    costo       numeric NOT NULL DEFAULT 0,  -- cuánto se pagó al proveedor
    usuario     text,
    creado_en   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_compras_externas_empresa_fecha
    ON public.compras_externas(empresa_id, creado_en);

ALTER TABLE public.compras_externas ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Verificación sugerida:
--   SELECT * FROM public.compras_externas ORDER BY creado_en DESC LIMIT 5;
