-- Migración 008: Costo real del repuesto en la orden + Gastos operativos
-- Motor: PostgreSQL (Supabase, proyecto flfhpffslhjcuvhxsnjz)
-- Implementa FASE 1 y FASE 3 del plan docs/PLAN_FINANZAS_Y_VENTAS.md
--
-- 1) ordenes.costo_repuesto_real: acumula cuánto COSTÓ de verdad el repuesto de la orden,
--    venga del stock (productos.costo) o de otro proveedor (compras_externas.costo).
--    Lo llena main.js automáticamente en 'usar-repuesto-lab' y 'registrar-repuesto-externo'.
--    Con esto la ganancia real por orden = (precio_repuesto − costo_repuesto_real) + precio_servicio.
--
-- 2) gastos: gastos operativos (alquiler, sueldos, luz, publicidad, etc.). Sin esto,
--    "ganancia neta" nunca puede ser real. Se restan al reporte por período.
--
-- La app usa la service_role key (bypassa RLS); RLS activado por consistencia con el resto.

BEGIN;

ALTER TABLE public.ordenes
    ADD COLUMN IF NOT EXISTS costo_repuesto_real numeric NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.gastos (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id  bigint  NOT NULL,
    categoria   text    NOT NULL DEFAULT 'Otros',
    descripcion text,
    monto       numeric NOT NULL CHECK (monto >= 0),
    fecha       date    NOT NULL DEFAULT CURRENT_DATE,
    usuario     text,
    creado_en   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_gastos_empresa_fecha ON public.gastos(empresa_id, fecha);

ALTER TABLE public.gastos ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Verificación sugerida:
--   SELECT column_name FROM information_schema.columns WHERE table_name='ordenes' AND column_name='costo_repuesto_real';
--   SELECT * FROM public.gastos LIMIT 1;
