-- Migración 009: Cierre de caja diario unificado (FASE 6 del plan docs/PLAN_FINANZAS_Y_VENTAS.md)
-- Motor: PostgreSQL (Supabase, proyecto flfhpffslhjcuvhxsnjz)
--
-- 1) ordenes.fecha_entregado: sello de CUÁNDO se entregó la orden. Sin esto no se puede saber
--    qué día se cobró el saldo (el adelanto se cobra al crear la orden; el saldo al entregar).
--    Lo llena main.js automáticamente cuando el estado pasa a 'Entregado'.
--
-- 2) cierres_dia: el "libro de caja" — una foto inmutable por día cuando el dueño cierra:
--    lo que entró (taller + ventas POS), lo que salió (gastos + compras externas + devoluciones)
--    y el neto. El detalle_json guarda el desglose completo de ese día.
--
-- La app usa la service_role key (bypassa RLS); RLS activado por consistencia con el resto.

BEGIN;

ALTER TABLE public.ordenes
    ADD COLUMN IF NOT EXISTS fecha_entregado timestamptz;

CREATE TABLE IF NOT EXISTS public.cierres_dia (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id       bigint  NOT NULL,
    fecha            date    NOT NULL,
    ingresos_taller  numeric NOT NULL DEFAULT 0,
    ingresos_pos     numeric NOT NULL DEFAULT 0,
    gastos           numeric NOT NULL DEFAULT 0,
    compras_externas numeric NOT NULL DEFAULT 0,
    devoluciones     numeric NOT NULL DEFAULT 0,
    neto             numeric NOT NULL DEFAULT 0,
    detalle_json     jsonb,
    usuario          text,
    creado_en        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_cierres_dia_empresa_fecha ON public.cierres_dia(empresa_id, fecha);

ALTER TABLE public.cierres_dia ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Verificación sugerida:
--   SELECT column_name FROM information_schema.columns WHERE table_name='ordenes' AND column_name='fecha_entregado';
--   SELECT * FROM public.cierres_dia LIMIT 1;
