-- Migración 011: Tiendas (sucursales) + ventas atribuidas a cada trabajador
-- ✅ YA APLICADA en producción el 2026-07-17 (vía MCP apply_migration) y probada.
--
-- Contexto: el negocio tiene 2 tiendas, cada una con técnico y vendedora. Se necesita
-- asignar personal por tienda y que cada trabajador vea SOLO sus propias ventas.
--
-- 1) tiendas: sucursales de cada empresa (gestión desde Escritorio → Usuarios).
-- 2) usuarios.tienda_id: a qué tienda pertenece cada trabajador.
-- 3) facturas.vendedor_usuario: quién generó cada comprobante. La vendedora ve solo SUS
--    boletas en su Cierre de Caja móvil; el escritorio también lo registra al emitir.
-- 4) generar_boleta_movil: nueva firma con p_vendedor DEFAULT NULL (reemplazo atómico
--    DROP+CREATE: la web publicada vieja sigue funcionando hasta desplegar la nueva).

BEGIN;

CREATE TABLE IF NOT EXISTS public.tiendas (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint NOT NULL,
    nombre     text   NOT NULL,
    creado_en  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_tiendas_empresa ON public.tiendas(empresa_id);
ALTER TABLE public.tiendas ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS tienda_id bigint;
ALTER TABLE public.facturas ADD COLUMN IF NOT EXISTS vendedor_usuario text;

DROP FUNCTION IF EXISTS public.generar_boleta_movil(bigint, text, text, text, numeric, jsonb, text);

CREATE OR REPLACE FUNCTION public.generar_boleta_movil(
    p_empresa_id bigint, p_cliente_nombre text, p_cliente_documento text,
    p_cliente_telefono text, p_monto_total numeric, p_items_json jsonb,
    p_metodo_pago text DEFAULT NULL::text, p_vendedor text DEFAULT NULL::text
)
RETURNS TABLE(id bigint, numero_comprobante text, created_at timestamp with time zone)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_siguiente_numero integer;
  v_numero_final text;
  v_ultima_factura text;
BEGIN
  IF p_monto_total IS NULL OR p_monto_total <= 0 THEN
    RAISE EXCEPTION 'Monto invalido';
  END IF;
  IF p_cliente_nombre IS NULL OR btrim(p_cliente_nombre) = '' THEN
    RAISE EXCEPTION 'El nombre del cliente es obligatorio';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended('facturas_boleta_' || p_empresa_id::text, 0));

  SELECT f.numero_comprobante INTO v_ultima_factura
  FROM facturas f
  WHERE f.empresa_id = p_empresa_id AND f.tipo = 'Boleta'
  ORDER BY f.id DESC
  LIMIT 1;

  v_siguiente_numero := 1;
  IF v_ultima_factura IS NOT NULL THEN
    v_siguiente_numero := COALESCE(NULLIF(split_part(v_ultima_factura, '-', 2), '')::integer, 0) + 1;
  END IF;

  v_numero_final := 'BBB-' || lpad(v_siguiente_numero::text, 4, '0');

  RETURN QUERY
  INSERT INTO facturas (empresa_id, numero_comprobante, tipo, cliente_documento, cliente_nombre, cliente_telefono, monto_total, items_json, metodo_pago, vendedor_usuario)
  VALUES (p_empresa_id, v_numero_final, 'Boleta', NULLIF(p_cliente_documento, ''), p_cliente_nombre, p_cliente_telefono, p_monto_total, p_items_json, p_metodo_pago, NULLIF(btrim(coalesce(p_vendedor,'')), ''))
  RETURNING facturas.id, facturas.numero_comprobante, facturas.created_at;
END;
$function$;

COMMIT;
