-- Semilla del catalogo compartido: los modelos que los talleres reales ya manejan.
-- Generada con variantesDeModelo() sobre los productos existentes (ver 018).
INSERT INTO modelos_dispositivos (marca,modelo,clave,estado,origen,creado_por) VALUES
('Samsung','Galaxy A01','A01','verificado','semilla',NULL),
('Honor','P. HONOR X8A','P. HONOR X8A','pendiente','semilla','6'),
('Honor','90 LITE','90 LITE','verificado','semilla',NULL),
('Honor','X50I','X50I','pendiente','semilla','6'),
('Samsung','A50S','A50S','verificado','semilla',NULL),
('Xiaomi','Mi 11 Lite','MI 11 LITE','verificado','semilla',NULL),
('Motorola','G04','G04','verificado','semilla',NULL),
('Motorola','G24','G24','verificado','semilla',NULL),
('Motorola','G24 POWER','G24 POWER','verificado','semilla',NULL),
('Motorola','E14','E14','verificado','semilla',NULL),
('Motorola','Moto C','MOTO C','pendiente','semilla','6'),
('Samsung','A02S','A02S','verificado','semilla',NULL),
('Samsung','A03','A03','verificado','semilla',NULL),
('Samsung','A03S','A03S','verificado','semilla',NULL),
('Samsung','A04E','A04E','verificado','semilla',NULL),
('Samsung','A03 CORE','A03 CORE','verificado','semilla',NULL),
('Samsung','A04S','A04S','verificado','semilla',NULL),
('Samsung','Galaxy A05','A05','verificado','semilla',NULL),
('Samsung','A05S','A05S','verificado','semilla',NULL),
('Samsung','Galaxy A06','A06','verificado','semilla',NULL),
('Samsung','A07','A07','verificado','semilla',NULL),
('Samsung','Galaxy A10','A10','verificado','semilla',NULL),
('Samsung','A10S','A10S','verificado','semilla',NULL),
('Samsung','Galaxy A11','A11','verificado','semilla',NULL),
('Samsung','Galaxy A12','A12','verificado','semilla',NULL),
('Samsung','A02','A02','verificado','semilla',NULL),
('Samsung','A13','A13','verificado','semilla',NULL),
('Samsung','A14 5G','A14 5G','verificado','semilla',NULL),
('Samsung','Galaxy A15','A15','verificado','semilla',NULL),
('Samsung','A16 5G','A16 5G','verificado','semilla',NULL),
('Samsung','A16','A16','verificado','semilla',NULL),
('Samsung','A20','A20','verificado','semilla',NULL),
('Samsung','Galaxy A20s','A20S','verificado','semilla',NULL),
('Samsung','A21','A21','verificado','semilla',NULL),
('Samsung','Galaxy A21s','A21S','verificado','semilla',NULL),
('Samsung','A22 4G','A22 4G','verificado','semilla',NULL),
('Samsung','Galaxy A24','A24','verificado','semilla',NULL),
('Samsung','A25','A25','verificado','semilla',NULL),
('Samsung','A26','A26','verificado','semilla',NULL),
('Samsung','A30','A30','verificado','semilla',NULL),
('Samsung','Galaxy A50','A50','verificado','semilla',NULL),
('Samsung','A30S','A30S','verificado','semilla',NULL),
('Samsung','Galaxy A31','A31','verificado','semilla',NULL),
('Samsung','Galaxy A32','A32','verificado','semilla',NULL),
('Samsung','A33','A33','verificado','semilla',NULL),
('Samsung','A34','A34','verificado','semilla',NULL),
('Samsung','Galaxy A51','A51','verificado','semilla',NULL),
('Samsung','A22 5G','A22 5G','verificado','semilla',NULL),
('Samsung','A35','A35','verificado','semilla',NULL),
('Samsung','A52','A52','verificado','semilla',NULL),
('Samsung','A53','A53','verificado','semilla',NULL),
('Samsung','A54','A54','verificado','semilla',NULL),
('Samsung','A55','A55','verificado','semilla',NULL),
('Samsung','J1 2016','J1 2016','verificado','semilla',NULL),
('Samsung','A23','A23','verificado','semilla',NULL),
('Motorola','Moto E 1st Gen','MOTO E 1ST GEN','pendiente','semilla','6'),
('ZTE','V70','V70','verificado','semilla',NULL),
('Samsung','J2 PRO','J2 PRO','verificado','semilla',NULL),
('Samsung','Galaxy J3','J3','verificado','semilla',NULL),
('Samsung','J4 PLUS','J4 PLUS','verificado','semilla',NULL),
('Samsung','J6 PLUS','J6 PLUS','verificado','semilla',NULL),
('Samsung','J5 2016','J5 2016','verificado','semilla',NULL),
('Samsung','J5','J5','verificado','semilla',NULL),
('Samsung','J5 PRO','J5 PRO','verificado','semilla',NULL),
('Samsung','J7 2016','J7 2016','verificado','semilla',NULL),
('Samsung','J7 NEO','J7 NEO','verificado','semilla',NULL),
('Samsung','J7 PRO','J7 PRO','verificado','semilla',NULL),
('Samsung','M31','M31','verificado','semilla',NULL),
('Samsung','Galaxy S20 FE','S20 FE','verificado','semilla',NULL),
('Samsung','S4','S4','verificado','semilla',NULL),
('Motorola','X PLAY','X PLAY','verificado','semilla',NULL),
('Motorola','E 2020','E 2020','verificado','semilla',NULL),
('Motorola','E13','E13','verificado','semilla',NULL),
('Motorola','E2','E2','verificado','semilla',NULL),
('Motorola','E20','E20','verificado','semilla',NULL),
('Motorola','E22','E22','verificado','semilla',NULL),
('Motorola','E22i','E22I','verificado','semilla',NULL),
('Motorola','E4','E4','verificado','semilla',NULL),
('Motorola','E30','E30','verificado','semilla',NULL),
('Motorola','E40','E40','verificado','semilla',NULL),
('Motorola','E5 PLAY','E5 PLAY','verificado','semilla',NULL),
('Motorola','E5','E5','verificado','semilla',NULL),
('Motorola','G6 PLAY','G6 PLAY','verificado','semilla',NULL),
('Motorola','E7','E7','verificado','semilla',NULL),
('Motorola','E7i','E7I','verificado','semilla',NULL),
('Motorola','E7 POWER','E7 POWER','verificado','semilla',NULL),
('Motorola','G5S PLUS','G5S PLUS','verificado','semilla',NULL),
('Motorola','G2','G2','verificado','semilla',NULL),
('Motorola','G34','G34','verificado','semilla',NULL),
('Motorola','G4','G4','verificado','semilla',NULL),
('Motorola','G4 PLAY','G4 PLAY','verificado','semilla',NULL),
('Motorola','G50','G50','verificado','semilla',NULL),
('Motorola','G53','G53','verificado','semilla',NULL),
('Motorola','G15','G15','verificado','semilla',NULL),
('Motorola','G05','G05','verificado','semilla',NULL),
('Motorola','E15','E15','verificado','semilla',NULL),
('Motorola','G10','G10','verificado','semilla',NULL),
('Motorola','G20','G20','verificado','semilla',NULL),
('Motorola','G30','G30','verificado','semilla',NULL),
('Motorola','G13','G13','verificado','semilla',NULL),
('Motorola','G23','G23','verificado','semilla',NULL),
('Motorola','G14','G14','verificado','semilla',NULL),
('Motorola','G54','G54','verificado','semilla',NULL),
('Motorola','G51','G51','verificado','semilla',NULL),
('Motorola','G60','G60','verificado','semilla',NULL),
('Motorola','G60S','G60S','verificado','semilla',NULL),
('Apple','iPhone 8','8','pendiente','semilla','6'),
('Motorola','G6 PLUS','G6 PLUS','verificado','semilla',NULL),
('Motorola','G7 PLAY','G7 PLAY','verificado','semilla',NULL),
('Motorola','G7','G7','verificado','semilla',NULL),
('Motorola','G7 PLUS','G7 PLUS','verificado','semilla',NULL),
('Motorola','G8 PLAY','G8 PLAY','verificado','semilla',NULL),
('Motorola','ONE MACRO','ONE MACRO','verificado','semilla',NULL),
('Motorola','G8 PLUS','G8 PLUS','verificado','semilla',NULL),
('Motorola','G8 POWER','G8 POWER','verificado','semilla',NULL),
('Motorola','G9 POWER','G9 POWER','verificado','semilla',NULL),
('Motorola','G9 PLAY','G9 PLAY','verificado','semilla',NULL),
('Motorola','E7 PLUS','E7 PLUS','verificado','semilla',NULL),
('Motorola','G9 PLUS','G9 PLUS','verificado','semilla',NULL),
('Realme','7i','7I','verificado','semilla',NULL),
('Motorola','Moto E 2nd Gen','MOTO E 2ND GEN','pendiente','semilla','6'),
('Honor','X7B','X7B','verificado','semilla',NULL),
('Honor','X8','X8','verificado','semilla',NULL),
('Honor','X8A','X8A','verificado','semilla',NULL),
('Honor','X8B','X8B','verificado','semilla',NULL),
('Honor','X9A','X9A','verificado','semilla',NULL),
('Vivo','Y36','Y36','verificado','semilla',NULL),
('Vivo','Y21S','Y21S','verificado','semilla',NULL),
('Sony','L2','L2','verificado','semilla',NULL),
('Sony','XA ULTRA','XA ULTRA','verificado','semilla',NULL),
('Tecno','GO 2023','GO 2023','verificado','semilla',NULL),
('Tecno','GO 2024','GO 2024','verificado','semilla',NULL),
('Realme','7 PRO','7 PRO','verificado','semilla',NULL),
('Realme','8 PRO','8 PRO','verificado','semilla',NULL),
('Realme','C11','C11','verificado','semilla',NULL),
('Realme','C11 2021','C11 2021','verificado','semilla',NULL),
('Realme','C21Y','C21Y','verificado','semilla',NULL),
('Realme','C55','C55','verificado','semilla',NULL),
('Realme','A58 4G','A58 4G','verificado','semilla',NULL),
('Xiaomi','NOTE 10 PRO 5G','NOTE 10 PRO 5G','verificado','semilla',NULL),
('Xiaomi','NOTE 10 PRO','NOTE 10 PRO','verificado','semilla',NULL),
('Xiaomi','11 PRO','11 PRO','verificado','semilla',NULL),
('Xiaomi','NOTE 11','NOTE 11','verificado','semilla',NULL),
('Xiaomi','NOTE 11S','NOTE 11S','verificado','semilla',NULL),
('Xiaomi','NOTE 12S','NOTE 12S','verificado','semilla',NULL),
('Xiaomi','NOTE 12','NOTE 12','verificado','semilla',NULL),
('Xiaomi','NOTE 12 4G','NOTE 12 4G','verificado','semilla',NULL),
('Xiaomi','NOTE 12 PRO 5G','NOTE 12 PRO 5G','verificado','semilla',NULL),
('Xiaomi','NOTE 12 PRO','NOTE 12 PRO','verificado','semilla',NULL),
('Xiaomi','Redmi Note 13','NOTE 13','verificado','semilla',NULL),
('Xiaomi','Redmi Note 14','NOTE 14','verificado','semilla',NULL),
('Xiaomi','NOTE 4','NOTE 4','verificado','semilla',NULL),
('Xiaomi','Redmi Note 8','NOTE 8','verificado','semilla',NULL),
('Xiaomi','Redmi Note 8 Pro','NOTE 8 PRO','verificado','semilla',NULL),
('Xiaomi','Redmi Note 9','NOTE 9','verificado','semilla',NULL),
('Xiaomi','NOTE 9 PRO','NOTE 9 PRO','verificado','semilla',NULL),
('Xiaomi','POCO F4','POCO F4','verificado','semilla',NULL),
('Xiaomi','POCO X3','POCO X3','verificado','semilla',NULL),
('Xiaomi','X3 PRO','X3 PRO','verificado','semilla',NULL),
('Xiaomi','REDMI 10 4G','10 4G','verificado','semilla',NULL),
('Xiaomi','REDMI 10C','10C','verificado','semilla',NULL),
('Xiaomi','REDMI 12C','12C','verificado','semilla',NULL),
('Xiaomi','REDMI 13C','13C','verificado','semilla',NULL),
('Xiaomi','POCO C65','POCO C65','verificado','semilla',NULL),
('Xiaomi','REDMI 14C','14C','verificado','semilla',NULL),
('Motorola','g05s','G05S','pendiente','semilla','6'),
('Samsung','A04','A04','verificado','semilla',NULL),
('Motorola','G22','G22','verificado','semilla',NULL),
('Motorola','E32','E32','verificado','semilla',NULL),
('Motorola','G5G','G5G','verificado','semilla',NULL),
('Motorola','G6','G6','verificado','semilla',NULL),
('Xiaomi','REDMI 7','7','verificado','semilla',NULL),
('Samsung','Galaxy A71','A71','verificado','semilla',NULL),
('Samsung','Galaxy A72','A72','verificado','semilla',NULL),
('Xiaomi','REDMI 7A','7A','verificado','semilla',NULL),
('Xiaomi','REDMI 9','9','verificado','semilla',NULL),
('Motorola','G8 POWER LITE','G8 POWER LITE','verificado','semilla',NULL),
('Xiaomi','Redmi Note 7','NOTE 7','verificado','semilla',NULL),
('Xiaomi','Redmi 9A','9A','verificado','semilla',NULL),
('Xiaomi','Redmi 9C','9C','verificado','semilla',NULL),
('Xiaomi','Redmi 10A','10A','verificado','semilla',NULL),
('Xiaomi','NOTE 10','NOTE 10','verificado','semilla',NULL),
('Xiaomi','10S','10S','verificado','semilla',NULL),
('Xiaomi','POCO M5S','POCO M5S','verificado','semilla',NULL),
('Xiaomi','M4 PRO','M4 PRO','verificado','semilla',NULL),
('Xiaomi','MI A2','MI A2','verificado','semilla',NULL),
('Xiaomi','Redmi 12 4G','12 4G','verificado','semilla',NULL),
('Xiaomi','Redmi 12 5G','12 5G','verificado','semilla',NULL),
('Xiaomi','Redmi 12T','12T','verificado','semilla',NULL),
('Xiaomi','Redmi 9i','9I','verificado','semilla',NULL),
('Apple','IPHONE 5G','5G','verificado','semilla',NULL),
('Xiaomi','Y19','Y19','verificado','semilla',NULL),
('Xiaomi','Redmi 8A','8A','verificado','semilla',NULL),
('Xiaomi','Redmi 8','8','verificado','semilla',NULL),
('Honor','X6c','X6C','verificado','semilla',NULL),
('Huawei','Y7 2019','Y7 2019','verificado','semilla',NULL),
('Huawei','Y7 2018','Y7 2018','verificado','semilla',NULL),
('Honor','X6b','X6B','verificado','semilla',NULL),
('Xiaomi','REDMI 9T','9T','verificado','semilla',NULL),
('Xiaomi','POCO M3','POCO M3','verificado','semilla',NULL),
('Xiaomi','REDMI A1','A1','verificado','semilla',NULL),
('Xiaomi','A2','A2','verificado','semilla',NULL),
('Xiaomi','REDMI A3','A3','verificado','semilla',NULL),
('Xiaomi','A3X','A3X','verificado','semilla',NULL),
('Xiaomi','REDMI 15','15','verificado','semilla',NULL),
('Huawei','Y6 2019','Y6 2019','verificado','semilla',NULL),
('Oppo','A16','A16','verificado','semilla',NULL),
('Huawei','Mate 20 lite','MATE 20 LITE','verificado','semilla',NULL),
('Huawei','P20','P20','verificado','semilla',NULL),
('Honor','X7','X7','verificado','semilla',NULL),
('Honor','X7a','X7A','verificado','semilla',NULL),
('Honor','X8c','X8C','verificado','semilla',NULL),
('Huawei','Y9 2019','Y9 2019','verificado','semilla',NULL),
('Huawei','Y8s','Y8S','verificado','semilla',NULL),
('Huawei','Nova 5i','NOVA 5I','verificado','semilla',NULL),
('Huawei','Nova 7i','NOVA 7I','verificado','semilla',NULL),
('Huawei','Y7p','Y7P','verificado','semilla',NULL),
('Huawei','P40 Lite','P40 LITE','verificado','semilla',NULL),
('Tecno','Spark 10C','SPARK 10C','verificado','semilla',NULL),
('Oppo','Reno 6 Lite','RENO 6 LITE','verificado','semilla',NULL),
('Tecno','Spark 10 Pro','SPARK 10 PRO','verificado','semilla',NULL),
('Oppo','A38','A38','verificado','semilla',NULL),
('Oppo','A78 4G','A78 4G','verificado','semilla',NULL),
('Oppo','A52','A52','verificado','semilla',NULL),
('Oppo','A53','A53','verificado','semilla',NULL),
('Apple','iPhone 12 Mini','12 MINI','verificado','semilla',NULL),
('Xiaomi','Mi 9 SE','MI 9 SE','verificado','semilla',NULL),
('Xiaomi','Redmi Note 6 Pro','NOTE 6 PRO','verificado','semilla',NULL),
('Xiaomi','Redmi Note 5 Pro','NOTE 5 PRO','verificado','semilla',NULL),
('LG','K50','K50','verificado','semilla',NULL),
('LG','Q60','Q60','verificado','semilla',NULL),
('LG','G4 STYLUS','G4 STYLUS','verificado','semilla',NULL),
('LG','K51','K51','verificado','semilla',NULL),
('Samsung','Galaxy A17','A17','verificado','semilla',NULL),
('Samsung','Galaxy A14','A14','verificado','semilla',NULL),
('Samsung','Galaxy A36 5G','A36 5G','verificado','semilla',NULL),
('Samsung','Galaxy A34 5G','A34 5G','verificado','semilla',NULL),
('Samsung','Galaxy A26 5G','A26 5G','verificado','semilla',NULL),
('Samsung','Galaxy A54 5G','A54 5G','verificado','semilla',NULL),
('Samsung','Galaxy S21 FE 5G','S21 FE 5G','verificado','semilla',NULL),
('Samsung','Galaxy A56 5G','A56 5G','verificado','semilla',NULL),
('Samsung','Galaxy S25 FE','S25 FE','verificado','semilla',NULL),
('Samsung','Galaxy S23 FE','S23 FE','verificado','semilla',NULL),
('Samsung','Galaxy J4','J4','verificado','semilla',NULL),
('Samsung','Galaxy J6','J6+','verificado','semilla',NULL),
('Samsung','Galaxy A25 5G','A25 5G','verificado','semilla',NULL),
('Oppo','A54','A54','verificado','semilla',NULL),
('Oppo','A57','A57','verificado','semilla',NULL),
('Oppo','A77','A77','verificado','semilla',NULL),
('Oppo','A17','A17','verificado','semilla',NULL),
('Oppo','A18','A18','verificado','semilla',NULL),
('Oppo','A78 5G','A78 5G','verificado','semilla',NULL),
('Oppo','RENO 7','RENO 7','verificado','semilla',NULL),
('Huawei','MATE 10','MATE 10','verificado','semilla',NULL),
('Huawei','NOVA 9 SE','NOVA 9 SE','verificado','semilla',NULL),
('Oppo','A80 5G','A80 5G','pendiente','semilla','6'),
('Xiaomi','7i','7I','verificado','semilla',NULL),
('Oppo','RENO 11','RENO 11','verificado','semilla',NULL),
('Xiaomi','NOTE 13 PRO 4G','NOTE 13 PRO 4G','verificado','semilla',NULL),
('Xiaomi','NOTE 14 PRO 4G','NOTE 14 PRO 4G','verificado','semilla',NULL),
('Xiaomi','REDMI NOTE 13 PRO 5G','NOTE 13 PRO 5G','verificado','semilla',NULL),
('Xiaomi','POCO X6','POCO X6','verificado','semilla',NULL),
('Huawei','P10','P10','verificado','semilla',NULL),
('Huawei','P10 LITE','P10 LITE','verificado','semilla',NULL),
('Huawei','P10 PLUS','P10 PLUS','verificado','semilla',NULL),
('Huawei','P30 LITE','P30 LITE','verificado','semilla',NULL),
('Huawei','P30 LITE ORIGEN','P30 LITE ORIGEN','verificado','semilla',NULL),
('Huawei','P8 LITE','P8 LITE','verificado','semilla',NULL),
('Huawei','P9 LITE','P9 LITE','verificado','semilla',NULL),
('Huawei','P9 LITE SMART','P9 LITE SMART','verificado','semilla',NULL),
('Huawei','PSMART 2017','PSMART 2017','verificado','semilla',NULL),
('Samsung','A56','A56','verificado','semilla',NULL),
('Samsung','A36','A36','verificado','semilla',NULL),
('Tecno','SPARK 20','SPARK 20','verificado','semilla',NULL),
('ZTE','A56','A56','verificado','semilla',NULL),
('ZTE','A36','A36','verificado','semilla',NULL),
('ZTE','A56PRO5G','A56PRO5G','verificado','semilla',NULL),
('ZTE','A76','A76','verificado','semilla',NULL),
('ZTE','A320','A320','verificado','semilla',NULL),
('Huawei','PSMART 2019','PSMART 2019','verificado','semilla',NULL),
('Huawei','PSMART 2019 ORIGEN','PSMART 2019 ORIGEN','verificado','semilla',NULL),
('Huawei','Y3 2017','Y3 2017','verificado','semilla',NULL),
('Huawei','Y5 LITE','Y5 LITE','verificado','semilla',NULL),
('Huawei','Y5 2019','Y5 2019','verificado','semilla',NULL),
('Huawei','Y5P','Y5P','verificado','semilla',NULL),
('Huawei','Y5 II','Y5 II','verificado','semilla',NULL),
('Huawei','Y6','Y6','verificado','semilla',NULL),
('Huawei','Y6 2018','Y6 2018','verificado','semilla',NULL),
('Huawei','Y6 II','Y6 II','verificado','semilla',NULL),
('Huawei','Y635','Y635','verificado','semilla',NULL),
('Huawei','Y8P','Y8P','verificado','semilla',NULL),
('Huawei','Y9 2018','Y9 2018','verificado','semilla',NULL),
('Huawei','Y9 PRIME','Y9 PRIME','verificado','semilla',NULL),
('Huawei','Y9S ORIGEN','Y9S ORIGEN','verificado','semilla',NULL),
('Huawei','Y9S','Y9S','verificado','semilla',NULL),
('Huawei','Y9A','Y9A','verificado','semilla',NULL),
('ZTE','A3 2019','A3 2019','verificado','semilla',NULL),
('ZTE','A5 2019','A5 2019','verificado','semilla',NULL),
('ZTE','V70 MAX','V70 MAX','verificado','semilla',NULL),
('ZTE','A3 LITE','A3 LITE','verificado','semilla',NULL),
('ZTE','A34','A34','verificado','semilla',NULL),
('ZTE','A54','A54','verificado','semilla',NULL),
('ZTE','A35','A35','verificado','semilla',NULL),
('ZTE','A55','A55','verificado','semilla',NULL),
('ZTE','A51','A51','verificado','semilla',NULL),
('ZTE','A71','A71','verificado','semilla',NULL),
('ZTE','A510','A510','verificado','semilla',NULL),
('ZTE','A521','A521','verificado','semilla',NULL),
('ZTE','A530','A530','verificado','semilla',NULL),
('ZTE','A531','A531','verificado','semilla',NULL),
('ZTE','A602','A602','verificado','semilla',NULL),
('ZTE','A610','A610','verificado','semilla',NULL),
('ZTE','A7 2019','A7 2019','verificado','semilla',NULL),
('ZTE','A5 2020','A5 2020','verificado','semilla',NULL),
('ZTE','A7 2020','A7 2020','verificado','semilla',NULL),
('ZTE','A7S 2020','A7S 2020','verificado','semilla',NULL),
('ZTE','V SMART','V SMART','verificado','semilla',NULL),
('ZTE','V10','V10','verificado','semilla',NULL),
('ZTE','V20 SMART','V20 SMART','verificado','semilla',NULL),
('ZTE','V30 VITA','V30 VITA','verificado','semilla',NULL),
('ZTE','V40 VITA','V40 VITA','verificado','semilla',NULL),
('ZTE','V50 DESIGN','V50 DESIGN','verificado','semilla',NULL),
('ZTE','V50 VITA','V50 VITA','verificado','semilla',NULL),
('ZTE','V6 PLUS','V6 PLUS','verificado','semilla',NULL),
('ZTE','V60 VITA','V60 VITA','verificado','semilla',NULL),
('ZTE','V8 SE','V8 SE','verificado','semilla',NULL),
('ZTE','V9 VITA','V9 VITA','verificado','semilla',NULL),
('Otros','A35E','A35E','pendiente','semilla','6'),
('Apple','IPHONE 5 SE','5 SE','verificado','semilla',NULL),
('Apple','IPHONE 6G','6G','verificado','semilla',NULL),
('Apple','IPHONE 6S','6S','verificado','semilla',NULL),
('Apple','IPHONE 6 PLUS','6 PLUS','verificado','semilla',NULL),
('Apple','IPHONE 6S PLUS','6S PLUS','verificado','semilla',NULL),
('Apple','IPHONE 7 PLUS','7 PLUS','verificado','semilla',NULL),
('Apple','IPHONE 8 PLUS','8 PLUS','verificado','semilla',NULL),
('Apple','IPHONE X','X','verificado','semilla',NULL),
('Apple','IPHONE XR','XR','verificado','semilla',NULL),
('Apple','IPHONE 11','11','verificado','semilla',NULL),
('Apple','IPHONE 11 PRO','11 PRO','verificado','semilla',NULL),
('Apple','IPHONE 12','12','verificado','semilla',NULL),
('Apple','iPhone 12 PRO','12 PRO','verificado','semilla',NULL),
('Apple','IPHONE XS MAX','XS MAX','verificado','semilla',NULL),
('Apple','IPHONE XS','XS','verificado','semilla',NULL),
('Xiaomi','REDMI 15C','15C','verificado','semilla',NULL),
('Honor','X6A','X6A','verificado','semilla',NULL),
('Honor','X6A PLUS','X6A PLUS','verificado','semilla',NULL),
('Honor','X5 PLUS','X5 PLUS','verificado','semilla',NULL),
('Apple','IPHONE 13','13','verificado','semilla',NULL),
('Nokia','2.1','2.1','verificado','semilla',NULL),
('Nokia','3.1','3.1','verificado','semilla',NULL),
('Nokia','5.1','5.1','verificado','semilla',NULL),
('Honor','50 LITE','50 LITE','verificado','semilla',NULL),
('Honor','MAGIC 5 LITE','MAGIC 5 LITE','verificado','semilla',NULL),
('Honor','MAGIC 6 LITE','MAGIC 6 LITE','verificado','semilla',NULL),
('Honor','MAGIC 7 LITE','MAGIC 7 LITE','verificado','semilla',NULL),
('Honor','X5B','X5B','verificado','semilla',NULL),
('Honor','X6','X6','verificado','semilla',NULL),
('Honor','X6S','X6S','verificado','semilla',NULL),
('Honor','X6B PLUS','X6B PLUS','verificado','semilla',NULL),
('Tecno','SPARK 20 PRO','SPARK 20 PRO','verificado','semilla',NULL),
('LG','G3 STYLUS','G3 STYLUS','verificado','semilla',NULL),
('LG','G5','G5','verificado','semilla',NULL),
('LG','K 51S','K 51S','verificado','semilla',NULL),
('LG','K20','K20','verificado','semilla',NULL),
('LG','K8','K8','verificado','semilla',NULL),
('LG','K8 2017','K8 2017','verificado','semilla',NULL),
('LG','K9','K9','verificado','semilla',NULL),
('LG','X POWER','X POWER','verificado','semilla',NULL),
('LG','X STYLE','X STYLE','verificado','semilla',NULL),
('Motorola','G5','G5','verificado','semilla',NULL),
('Motorola','G5 MÁQUINA','G5 MÁQUINA','verificado','semilla',NULL),
('Motorola','G3','G3','verificado','semilla',NULL),
('Motorola','G4 PLUS','G4 PLUS','verificado','semilla',NULL),
('Huawei','NOVA 8i','NOVA 8I','verificado','semilla',NULL),
('Huawei','P SMART 2019','P SMART 2019','verificado','semilla',NULL),
('Huawei','P30','P30','verificado','semilla',NULL),
('LG','K4 2017','K4 2017','verificado','semilla',NULL),
('Realme','9i','9I','verificado','semilla',NULL),
('Oppo','A58','A58','verificado','semilla',NULL),
('Xiaomi','POCO F3','POCO F3','verificado','semilla',NULL),
('LG','G4 STYLE NO','G4 STYLE NO','verificado','semilla',NULL),
('LG','K4','K4','verificado','semilla',NULL),
('Xiaomi','NOTE 9T','NOTE 9T','verificado','semilla',NULL),
('Motorola','G56','G56','verificado','semilla',NULL),
('Xiaomi','REDMI NOTE 11 4G','NOTE 11 4G','verificado','semilla',NULL),
('Xiaomi','READMI 2 LITE','READMI 2 LITE','verificado','semilla',NULL),
('Xiaomi','MI A2 LITE','MI A2 LITE','verificado','semilla',NULL),
('Samsung','AO2','AO2','verificado','semilla',NULL),
('Oppo','A57 4G','A57 4G','verificado','semilla',NULL),
('Huawei','Mate note 10','MATE NOTE 10','pendiente','semilla','6')
ON CONFLICT (marca,clave) DO NOTHING;
