-- ============================================================================
-- 029 — Repartidores de tarjetas: a quién le entregaron y qué venta trajo cada uno
-- ============================================================================
-- Motor: PostgreSQL (Supabase, proyecto flfhpffslhjcuvhxsnjz)
--
-- POR QUÉ
-- Las tarjetas de presentación se van a repartir con repartidores que cobran comisión
-- por licencia vendida. Hoy no hay forma de saber quién trajo a quién: el QR de la
-- tarjeta apunta a caracteristicas.html, el mismo para todos, y `licencias` solo guarda
-- el código y si se usó.
--
-- DECISIÓN: UN SOLO QR, EL CLIENTE ELIGE
-- No se imprime un QR por repartidor. La página pregunta "¿quién te dio la tarjeta?"
-- justo antes de abrir WhatsApp, y el código del repartidor viaja escrito en el texto
-- pre-llenado del mensaje. Eso sobrevive el salto a la app de WhatsApp, que es donde se
-- pierden las cookies y las sesiones. Ventaja práctica: las tarjetas YA impresas sirven
-- tal cual, no hay que reimprimir nada.
--
-- POR QUÉ LA COMISIÓN VA EN `licencias` Y NO EN UNA TABLA APARTE
-- Una venta = una licencia = una comisión. Metiéndola como columnas de esa misma fila no
-- hay dos registros que se puedan desincronizar, y el momento en que se emite el código
-- es exactamente el momento en que se sabe quién refirió al comprador.
--
-- `leads` NO es para pagar. El pago es solo por venta cerrada (decisión del dueño). Los
-- leads y las entregas sirven para atribuir: si un taller escribe sin decir quién le dio
-- la tarjeta, se busca ese taller en `entregas` y aparece qué repartidor lo visitó.
--
-- ACCESO
-- Las tres tablas son de la casa matriz, no de un taller: no llevan empresa_id. Se cierran
-- a anon/authenticated y quedan accesibles con la clave de servicio (o sea, vía /api/db,
-- que valida rol y token del lado del servidor) más una política para la matriz, por si
-- algún día se consultan desde la app de escritorio con la clave pública.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) Repartidores
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.repartidores (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        text NOT NULL,
    -- El que ve el cliente en la lista "¿quién te dio la tarjeta?". Si hay dos Juan,
    -- acá se desempata ("Juan P. — Gamarra"); por eso está separado de `nombre`.
    nombre_publico text NOT NULL,
    telefono      text,
    zona          text,
    -- Viaja en el texto del WhatsApp, así que se restringe a caracteres que no se
    -- rompan al codificar la URL ni se confundan al leerlos en el chat.
    codigo        text NOT NULL UNIQUE CHECK (codigo ~ '^[A-Z0-9]{2,16}$'),
    -- Su link personal para registrar entregas (mismo patrón que ordenes.tracking_token:
    -- sin contraseña, el que tiene el link es él).
    token         uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    comision_pct  numeric NOT NULL DEFAULT 10 CHECK (comision_pct >= 0 AND comision_pct <= 100),
    activo        boolean NOT NULL DEFAULT true,
    creado_en     timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.repartidores IS
    'Gente que reparte las tarjetas de presentación a cambio de comisión por licencia vendida. Es de la casa matriz: no tiene empresa_id.';
COMMENT ON COLUMN public.repartidores.codigo IS
    'Código corto que viaja en el mensaje pre-llenado de WhatsApp (ej. JUAN01). Solo A-Z y 0-9 para que no se rompa al codificar la URL.';
COMMENT ON COLUMN public.repartidores.token IS
    'Link personal para registrar entregas desde el celular, sin contraseña. Si se filtra, se regenera con un UPDATE.';

-- ---------------------------------------------------------------------------
-- 2) Entregas: qué taller visitó cada repartidor
-- ---------------------------------------------------------------------------
-- No se paga por esto. Sirve para (a) atribuir cuando el cliente no dice quién le dio la
-- tarjeta, y (b) saber qué zonas ya están cubiertas y no mandar a dos personas al mismo
-- local.
CREATE TABLE IF NOT EXISTS public.entregas (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repartidor_id  bigint NOT NULL REFERENCES public.repartidores(id) ON DELETE CASCADE,
    taller_nombre  text NOT NULL,
    direccion      text,
    distrito       text,
    contacto       text,
    telefono       text,
    notas          text,
    creado_en      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS entregas_repartidor_idx
    ON public.entregas (repartidor_id, creado_en DESC);
-- Para buscar "¿quién visitó este taller?" cuando alguien escribe sin decir de dónde salió.
CREATE INDEX IF NOT EXISTS entregas_taller_idx
    ON public.entregas (lower(taller_nombre));

COMMENT ON TABLE public.entregas IS
    'Talleres donde un repartidor dejó tarjeta. No genera pago (solo se paga por venta); es la red de seguridad para atribuir un lead que no dijo quién le dio la tarjeta.';

-- ---------------------------------------------------------------------------
-- 3) Leads: quién escaneó y a quién dijo que se lo dio
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.leads (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- NULL a propósito: el visitante pudo elegir "no recuerdo" o llegar sin tarjeta.
    -- Igual se guarda la fila, porque después él puede preguntarlo por WhatsApp y
    -- completarlo a mano desde el panel.
    repartidor_id  bigint REFERENCES public.repartidores(id) ON DELETE SET NULL,
    origen         text NOT NULL DEFAULT 'tarjeta'
                   CHECK (origen IN ('tarjeta', 'web', 'otro')),
    -- Identificador aleatorio del navegador (localStorage). NO es la IP ni el user agent:
    -- solo sirve para que el mismo visitante tocando WhatsApp cinco veces sea un lead y
    -- no cinco. No identifica a una persona ni se cruza con nada más.
    visitante      uuid,
    creado_en      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS leads_repartidor_idx
    ON public.leads (repartidor_id, creado_en DESC);
CREATE UNIQUE INDEX IF NOT EXISTS leads_visitante_repartidor_idx
    ON public.leads (visitante, repartidor_id)
    WHERE visitante IS NOT NULL;

COMMENT ON TABLE public.leads IS
    'Un toque al botón de WhatsApp desde caracteristicas.html, con el repartidor que el visitante eligió. No se paga por lead: es señal de a quién atribuir la venta si después compra.';

-- ---------------------------------------------------------------------------
-- 4) La comisión vive en la licencia
-- ---------------------------------------------------------------------------
-- comision_estado arranca en 'na' para que las 5 licencias que ya existen no queden
-- marcadas como si le debieran plata a alguien.
ALTER TABLE public.licencias
    ADD COLUMN IF NOT EXISTS repartidor_id      bigint REFERENCES public.repartidores(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS venta_monto        numeric CHECK (venta_monto IS NULL OR venta_monto >= 0),
    ADD COLUMN IF NOT EXISTS comision_monto     numeric CHECK (comision_monto IS NULL OR comision_monto >= 0),
    ADD COLUMN IF NOT EXISTS comision_estado    text NOT NULL DEFAULT 'na',
    ADD COLUMN IF NOT EXISTS comision_pagada_en timestamptz;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'licencias_comision_estado_check') THEN
        ALTER TABLE public.licencias
            ADD CONSTRAINT licencias_comision_estado_check
            CHECK (comision_estado IN ('na', 'pendiente', 'pagada'));
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS licencias_repartidor_idx
    ON public.licencias (repartidor_id)
    WHERE repartidor_id IS NOT NULL;

COMMENT ON COLUMN public.licencias.repartidor_id IS
    'Quién refirió esta venta. Se pone a mano al emitir el código, con lo que dijo el cliente o con lo que aparece en entregas/leads.';
COMMENT ON COLUMN public.licencias.comision_estado IS
    'na = sin repartidor. pendiente = se le debe. pagada = ya se le pagó (ver comision_pagada_en).';

-- ---------------------------------------------------------------------------
-- 5) Cerrar el acceso directo
-- ---------------------------------------------------------------------------
-- Supabase otorga permisos a anon/authenticated por defecto en cada tabla nueva. Estas
-- tres no se tocan nunca desde el navegador: todo pasa por /api/db, que corre en el
-- servidor con la clave de servicio y valida rol/token antes de escribir. Sin este
-- REVOKE, la anon key (que es pública por diseño) alcanzaría para leer los teléfonos de
-- los repartidores y la lista de talleres visitados.
REVOKE ALL ON public.repartidores FROM anon, authenticated;
REVOKE ALL ON public.entregas     FROM anon, authenticated;
REVOKE ALL ON public.leads        FROM anon, authenticated;

ALTER TABLE public.repartidores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entregas     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads        ENABLE ROW LEVEL SECURITY;

-- Misma regla que `licencias` en la 022: esto es de la casa matriz y de nadie más. La
-- clave de servicio se salta el RLS por diseño, así que /api/db sigue funcionando.
DROP POLICY IF EXISTS bh_repartidores_matriz ON public.repartidores;
CREATE POLICY bh_repartidores_matriz ON public.repartidores
    FOR ALL TO authenticated
    USING (public.soy_matriz()) WITH CHECK (public.soy_matriz());

DROP POLICY IF EXISTS bh_entregas_matriz ON public.entregas;
CREATE POLICY bh_entregas_matriz ON public.entregas
    FOR ALL TO authenticated
    USING (public.soy_matriz()) WITH CHECK (public.soy_matriz());

DROP POLICY IF EXISTS bh_leads_matriz ON public.leads;
CREATE POLICY bh_leads_matriz ON public.leads
    FOR ALL TO authenticated
    USING (public.soy_matriz()) WITH CHECK (public.soy_matriz());

-- ============================================================================
-- ROLLBACK (pegar en el SQL Editor si hay que volver atrás)
-- ============================================================================
-- DROP TABLE IF EXISTS public.leads;
-- DROP TABLE IF EXISTS public.entregas;
-- DROP TABLE IF EXISTS public.repartidores;
-- ALTER TABLE public.licencias
--     DROP CONSTRAINT IF EXISTS licencias_comision_estado_check,
--     DROP COLUMN IF EXISTS repartidor_id,
--     DROP COLUMN IF EXISTS venta_monto,
--     DROP COLUMN IF EXISTS comision_monto,
--     DROP COLUMN IF EXISTS comision_estado,
--     DROP COLUMN IF EXISTS comision_pagada_en;
-- ============================================================================
